package com.arman.dev.androiddocumentation.questions

/**
 * what is data class?
 * A data class in Kotlin is a class specifically designed to hold data.
 * Declared with the data keyword, Kotlin automatically generates several
 * useful methods based on the properties declared in the primary constructor.
 * data from api.
 * data from database is modeled using the data class.
 * it should have at least one property.
 * it cant be open/abstract/sealed.
 *
 * compiler automatically generates some methods for it, without the data class we manually
 * have to write the implementation of these methods, which eventually will increase the boiler
 * plate code.
 * 1.equal()
 * 2.copy()
 * 3.hash()
 * 4.componentN()
 *
 * equals() is used for checking the structural equality.(parameter as well as type of object)
 * and equality is checked based on the values or property.
 */

/**
 * why it should have at least one property in the constructor of data of data class.
 * because the methods like copy,hashcode,equals,componentN are generated based on the
 * constructor value.
 */

/**
 * what is structural equality?
 * structural equality is checking the equality of the parameter value of primary
 * constructor of the same type of object.
 * it checks for the parameter values of the primary constructor.
 */

data class Person(
    val name : String ,
    val age :Int ,
    val height :Int
){
    fun checkStructuralEquality(person : Person): Boolean{
     return person == this
    }
}

data class Employee(
    val name: String,       // ✅ included in equals, hashCode, toString, copy
    val department: String  // ✅ included
) {
    var salary: Double = 0.0  // ❌ NOT included — declared in body
}
data class User1(
    val name : String
)

fun main(){
//    val ob1 = User1("arman")
//    val ob2 = User1("arman")
//
//    println(ob1==ob2)
//    println(ob1===ob2)
//
//    println(ob1.equals(ob2))
//    println(ob1.hashCode())
//    println(ob1.component1())
    val a = X(
        a = 123
    )
    val b = Y(
        b = 123
    )

    val c = Y(
        b = 123
    )

    val d = Z(
        name = "Arman",
        age = 23,
        color = "yellow"
    )

    val ( x, y ) = d

    println(
        x
    )
    println(
        y
    )

    println(
        c.component1()
    )

    println(a.hashCode())
    println(b.hashCode())
    println(c.hashCode())

    println(
        Person("Arman" , 23 , 5).checkStructuralEquality(
            Person("Arman" , 23 , 5)
        )
    )


    val ob1 = User2(5)
    val ob2 = User3(5)

    println(ob1.equals(ob2))
    println(ob1.hashCode())
    println(ob2.hashCode())
    println(ob1 == ob2)

}

/**
 * what is the benefit of the data class over the other class holding the data from the
 * api or databases.
 *
 * Data class automatically generates some inbuilt function which makes easy for managing
 * and holding the data.
 * if we create our own custom class for holding the data we need to provide the implementation
 * of methods like copy() , equals() , hashcode() , componentN(), toString() which eventually lead to
 * increase in boiler plate code.
 */

/**
 * what are the different methods data class provides ? what are their uses?
 * .copy()
 * .equals()
 * .hashcode()
 * .componentN()
 * .toString()
 */

// this is the implementation of the copy function.
data class Phone(
    val size :Int ,
    val color : String,
){
   fun Copy(s :Int = this.size , color: String = this.color): Phone{
        return Phone(
            s,
            color
        )
    }
}
/**
 * copy function->>
 * copy is an in built function provided by the compiler which is used to create and instance
 * of data class by modifying the object and reusing some of its property and some new property.
 */

/**
 * equals() function->>
 * equals function is a function which is provided by the compiler to compare the two instances
 * of the data class.
 * it checks for the same properties.
 * it checks for the same type of object.
 * if both comes out to be equal then it will return the true value.
 */


/**
 * hashcode()-->>
 * hashcode is an inbuilt function that is generated by the kotlin compiler used to generate
 * the hashcode for the instances of data class.
 * it generates the hashcode from the property of instances.
 * it does not depends upon the type of instances.
 * it checks only the property value.
 */

data class X(
    val a : Int
)
data class Y(
    val b: Int
)

/**
 * componentN()
 * it is inbuilt function which is generated by the compiler which returns the component.
 * as much as component are there, there should be equal number of component.
 * it allows to extract the multiple value from the object easily.
 */

data class Z(
    val name : String ,
    val age :Int ,
    val color : String
)

/**
 * why data class can never be 1.open 2.abstract 3.sealed 4.inner
 * 1.why it cant be open
 */

/**
open data class Animal (val name : String)
data class dog(val name : String , val breed : String): Animal(name)
in hypothetical situation lets say data class Animal is open ,it has name property in its
 constructor.
 another data class dog has name and breed in its constructor and it is inheriting the animal class
 each data class will have the equals() function generated by compiler.
 when we do dog.equals(animal) ->> false
 when we do animal.equals(dog) ->> true so this will break the consistency.
*/

/**
 * data class can implement the interfaces.
 * data class can extend the abstract class.
 */

interface Printable{
    fun print()
}

data class Invoice(
    val id :String ,
    val amount : Double
): Printable{
    override fun print() {
        println("Invoice-> $id amount-> $amount")
    }
}


abstract class Shape(val color: String)
data class Circle(val radius: Double, val shapeColor: String) : Shape(shapeColor) {
    fun printShape() {
        println(super.color)
        println(shapeColor)
    }
}

/**
 * why data class cant be sealed?
 * sealed class is meant to be subclassed means there would the subclasses of it.
 * but a data class is a self contained data holder.These two intention directly
 * contradict each other.
 *
 * sealed data class Result(val status :String)
 * data class Success(val msg :String) :Result("ok")
 *
 * hypothetically compiler will generate the equals function for the Result class and when
 * it is compared with Success("no") it will return true because both have the status "OK"
 * which is dangerous.
 */


/**
 * why data class cant be abstract?
 * abstract data class is to be extended.
 * it cant be instantiated, and data class need to be instantiated.
 * some one will extend and will add some property to the data class.
 * again the same problem of equals() will arise.
 * issue with copy() , because the abstract class cant be instantiated so what will
 * it return when applied copy method.
 */

/**
 * why it cant be inner?
 * inner class keep the reference to the instance of the outer class.
 * in hypothetical world,
 * class Graph{
 * inner data class Node(val node :Int)
 * }
 * val g1 = Graph()
 * val g2 = Graph()
 * val n1 = g1.Node()
 * val n2 = g2.Node()
 *
 * n1==n1 ?? what will this result. true ? both are belonging to the different group.
 * so this will be causing the silent bug.
 *
 * inconsistency in hashcode , because both will generate the same hashcode but they belongs
 * to the different Groups and keeping them into hash will cause issues.
 */

/**
 * implementation of the copy() , equals() ,hashcode() , componentsN() , toString()
 */

/**
 * copy()
 */
data class Charger(
    val name : String ,
    val power : Int ,
    val color: String
){
    fun copyInstance(
        name: String = this.name,
        power: Int = this.power,
        color: String = this.color
    ): Charger = Charger(
            name = name ,
            power = power ,
            color = color
        )

    fun compareEquals(other : Any?): Boolean{
        if(this === other) return true  //same reference

        if(other==null || other !is Charger) return false //null and type

        return this.name == other.name &&
                this.color == other.color &&
                this.power == other.power

    }

    override fun hashCode(): Int {
        var result = name.hashCode()
        result = result*31 + power.hashCode()
        result = result*31 +color.hashCode()
        return  result
    }

    override fun toString(): String {
        return "Charger(name = ${this.name},power = ${this.power}, color = ${this.color})"
    }

//   operator fun component1(): String = name

}


open class A{
    internal  val x: String = "Arman"
}

data class User2(
    val name : Int
)

data class User3(
    val name : Int
)


